name: school_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>= 2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2



  flutter_bloc: ^8.1.2
  conditional_builder_null_safety: ^0.0.6

  dio: ^5.1.1
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.1.0

  intl: ^0.18.0

  flutter_staggered_animations: ^1.1.1
  animations: ^2.0.7



  animated_text_kit: ^4.2.2
  flutter_staggered_grid_view: ^0.6.2
  flutter_custom_clippers: ^2.1.0
  flash: ^3.0.5+1
  syncfusion_flutter_datepicker: ^22.2.8
  cached_network_image: ^3.2.3
  lottie: ^2.3.2
  dropdown_button2: ^2.3.7
  image_picker: ^1.0.2


  email_validator: ^2.1.17

  sensors_plus: ^3.0.0

  simple_animations: ^4.2.0
  flutter_spinkit: ^5.2.0

  flutter_styled_toast: ^2.1.3
  awesome_snackbar_content: ^0.1.3
  fluttertoast: ^8.2.1

  file_picker: ^5.3.2

  flutter_screenutil: ^5.8.4

  chewie: ^1.7.0

  percent_indicator: ^4.2.3

  emoji_picker_flutter: ^1.6.1

  keyboard_emoji_picker: ^1.0.3

  timeago: ^3.5.0

  awesome_dialog: ^3.1.0

  video_player: ^2.7.0

  firebase_core: ^2.15.0

  firebase_messaging: ^14.6.5
  firebase_app_check: ^0.1.5+1
  firebase_analytics: ^10.4.4

  flutter_local_notifications: ^15.1.0+1


  flutter_launcher_icons: ^0.13.1

  introduction_screen: ^3.1.11

  animated_splash_screen: ^1.3.0

  page_transition: ^2.0.9

  flutter_chat_bubble: ^2.0.2
  shimmer: ^3.0.0

  path_provider: ^2.1.0

  permission_handler: ^10.4.3

  flutter_file_downloader: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/home/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/home/logo.png"
  image_path_ios: "assets/home/logo.png"

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/home/school2.jpeg
    - assets/home/school3.jpeg
    - assets/home/school4.jpeg
    - assets/home/image_2.png
    - assets/home/logo.png
    - assets/image/
    - assets/images/articles/
    - assets/images/marks/
    - assets/images/notific/
    - assets/images/courses/
    - assets/home/
    - assets/animations/
    - assets/image/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
