name: school_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>= 2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  flutter_bloc: ^8.1.2
  conditional_builder_null_safety: ^0.0.6

  dio: ^5.1.1
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.1.0

  intl: ^0.17.0

  flutter_staggered_animations: ^1.1.1
  animations: ^2.0.7

  email_validator: ^2.1.17

  sensors_plus: ^3.0.0

  simple_animations: ^4.2.0
  flutter_spinkit: ^5.2.0

  flutter_styled_toast: ^2.1.3
  awesome_snackbar_content: ^0.1.3
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/home/school2.jpeg
    - assets/home/school3.jpeg
    - assets/home/school4.jpeg
    - assets/home/image_2.png
    - assets/home/logo.png



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
